[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@10.17.0 && pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build --filter=@caeli/backend"]

[start]
cmd = "cd apps/backend && pnpm start"
